### ISSUE TITLE
AssertionError: getItemComposition must be called on client thread

### ISSUE THREAD

**Issue by emerald000** [botanicvelious/Equipment-Inspector#8]
When you try to inspect someone with assertions enabled, you receive the following error:

```
[AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AssertionError: getItemComposition must be called on client thread
	at net.runelite.client.game.ItemManager.getItemComposition(ItemManager.java:386)
	at net.runelite.client.game.ItemManager.getItemPrice(ItemManager.java:308)
	at net.runelite.client.game.ItemManager.getItemPrice(ItemManager.java:287)
	at equipmentinspector.EquipmentInspectorPanel.lambda$null$0(EquipmentInspectorPanel.java:99)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at equipmentinspector.EquipmentInspectorPanel.lambda$update$1(EquipmentInspectorPanel.java:96)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by LordFrz** [comment]
I am getting the same issue

**Comment by ShaunDreclin** [comment]
I'm getting this issue when I run my snapshot build, but turning off devtools doesn't prevent it.

**Comment by botanicvelious** [comment]
I am currently busy with school but if anyone wants to submit a patch ill merge it
